import type { Metadata } from 'next'
// import Image from 'next/image'
// import { Geist, Geist_Mono } from 'next/font/google'

import '../../app/globals.css'
import PlausibleProvider from 'next-plausible'
// import Header from '@/components/demo/Header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <PlausibleProvider
                    domain="castr.guru"
                    customDomain="https://plausible.castr.guru"
                >
                    {children}
                </PlausibleProvider>
            </body>
        </html>
    )
}
